package com.georgeinfo.exceldb;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.write.style.ColumnWidth;

public class TestTableHeader {
    @ColumnWidth(50)
    @ExcelProperty({"ID"})
    private Integer id;

    @ColumnWidth(50)
    @ExcelProperty({"姓名"})
    private String name;

    @ColumnWidth(150)
    @ExcelProperty({"地址"})
    private String address;

    public TestTableHeader() {
    }

    public TestTableHeader(Integer id, String name, String address) {
        this.id = id;
        this.name = name;
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.id
     *
     * @return the value of test_table.id
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.id
     *
     * @param id the value for test_table.id
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.name
     *
     * @return the value of test_table.name
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.name
     *
     * @param name the value for test_table.name
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.address
     *
     * @return the value of test_table.address
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.address
     *
     * @param address the value for test_table.address
     * @mbg.generated Wed May 24 23:47:33 CST 2023
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}