package com.georgeinfo.model;

public class TestTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.id
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.name
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.address
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.id
     *
     * @return the value of test_table.id
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.id
     *
     * @param id the value for test_table.id
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.name
     *
     * @return the value of test_table.name
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.name
     *
     * @param name the value for test_table.name
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.address
     *
     * @return the value of test_table.address
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.address
     *
     * @param address the value for test_table.address
     *
     * @mbg.generated Sun Jun 18 23:33:18 CST 2023
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}